# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a82c37e540a32430097b0944089eaae7c967a5427254ced6fc1452b4e30817c7e564db7af90a961ed250f5869f464493354c082b11926a2d94223fd58797521

test:
  secret_key_base: 247b5a81eae73aac125db197d1c7d44e8e3a8aa72044402a397d202f5e5b79b8bfcfbff73ba49b03282d53a987f063fc42136a7e790cbac0491a3b3527fe173b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
